# Generated by Django 5.1.1 on 2024-12-11 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210707_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 2, 27, 9, 109091)),
        ),
    ]
