# Generated by Django 5.1.1 on 2024-12-12 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_contact_date_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 7, 30, 12, 320580)),
        ),
    ]
